name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # Remplace par le nom de ta branche si nécessaire

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .  # Remplace par le dossier où se trouve ton site (ex: `public` si nécessaire)
